-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Prestamos"
(
    "FechaIni" date NOT NULL,
    "FechaFin" date NOT NULL,
    "Cod_Socio" integer NOT NULL,
    "Cod_Libro" integer NOT NULL,
    "Cod_Prestamo" serial NOT NULL,
    CONSTRAINT "Prestamos_pkey" PRIMARY KEY ("Cod_Prestamo")
);

CREATE TABLE IF NOT EXISTS public."Socio"
(
    "Nombre" character varying(60) COLLATE pg_catalog."default" NOT NULL,
    "Direccion " character varying(120) COLLATE pg_catalog."default" NOT NULL,
    "Cod_Socio" serial NOT NULL,
    CONSTRAINT "Socio_pkey" PRIMARY KEY ("Cod_Socio")
);

CREATE TABLE IF NOT EXISTS public."Tema"
(
    "Nombre" character varying(60) COLLATE pg_catalog."default" NOT NULL,
    "Cod_Tema" serial NOT NULL,
    CONSTRAINT "Tema_pkey" PRIMARY KEY ("Cod_Tema")
);

CREATE TABLE IF NOT EXISTS public."Libro"
(
    "Nombre" character varying(60) NOT NULL,
    "Cod_Libro" serial NOT NULL,
    "Autor" character varying NOT NULL,
    "NumEjem" integer NOT NULL,
    "Cod_Tema" integer NOT NULL,
    PRIMARY KEY ("Cod_Libro")
);

ALTER TABLE IF EXISTS public."Prestamos"
    ADD CONSTRAINT "FK_prestamos_socios" FOREIGN KEY ("Cod_Socio")
    REFERENCES public."Socio" ("Cod_Socio") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Prestamos"
    ADD CONSTRAINT "FK_prestamos_libros" FOREIGN KEY ("Cod_Libro")
    REFERENCES public."Libro" ("Cod_Libro") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Libro"
    ADD CONSTRAINT "FK_libros_temas" FOREIGN KEY ("Cod_Tema")
    REFERENCES public."Tema" ("Cod_Tema") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;