-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Socio"
(
    "Cód.Socio" serial NOT NULL,
    "Nombre" character varying(60) NOT NULL,
    "Direccion " character varying(120) NOT NULL,
    PRIMARY KEY ("Cód.Socio")
);

CREATE TABLE IF NOT EXISTS public."Libro"
(
    "Cód.Libro " serial NOT NULL,
    "Titulo" character varying(60) NOT NULL,
    "Autor" character varying(60) NOT NULL,
    "NumEjem" integer NOT NULL,
    "Cód.Temas" integer NOT NULL,
    PRIMARY KEY ("Cód.Libro ")
);

CREATE TABLE IF NOT EXISTS public."Tema"
(
    "Cód.Tema" serial NOT NULL,
    "Nombre" character varying NOT NULL,
    PRIMARY KEY ("Cód.Tema")
);

CREATE TABLE IF NOT EXISTS public."Prestamos"
(
    "Cód.Prestamo" serial NOT NULL,
    "FechaIni" date NOT NULL,
    "FechaFin" date NOT NULL,
    "Cód.Socio" integer NOT NULL,
    "Cód.Libro" integer NOT NULL,
    PRIMARY KEY ("Cód.Prestamo")
);

ALTER TABLE IF EXISTS public."Libro"
    ADD CONSTRAINT "FK_libros_temas" FOREIGN KEY ("Cód.Temas")
    REFERENCES public."Tema" ("Cód.Tema") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Prestamos"
    ADD CONSTRAINT "FK_prestamos_socios" FOREIGN KEY ("Cód.Socio")
    REFERENCES public."Socio" ("Cód.Socio") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Prestamos"
    ADD CONSTRAINT "Fk_prestamos_libros" FOREIGN KEY ("Cód.Libro")
    REFERENCES public."Libro" ("Cód.Libro ") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;