-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Autobuses"
(
    "Cod_Bus" integer NOT NULL,
    "Kilometraje" numeric(7, 2) NOT NULL,
    "Matricula" character varying(8) COLLATE pg_catalog."default" NOT NULL,
    "Plazas" integer NOT NULL,
    "Modelo" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Autobuses_pkey" PRIMARY KEY ("Cod_Bus")
);

CREATE TABLE IF NOT EXISTS public."Conductor"
(
    "Cod_Conductor" integer NOT NULL,
    "DNI" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Nombre" character varying(60) COLLATE pg_catalog."default" NOT NULL,
    "Salario" numeric(6, 2) NOT NULL,
    "Edad" integer NOT NULL,
    "Teléfono" numeric(9, 0) NOT NULL,
    "Experiencia" integer NOT NULL,
    CONSTRAINT "Conductor_pkey" PRIMARY KEY ("Cod_Conductor")
);

CREATE TABLE IF NOT EXISTS public."Lugares"
(
    "Nombres" character varying COLLATE pg_catalog."default" NOT NULL,
    "Cod_Lugares" integer NOT NULL DEFAULT nextval('"Lugares_Cod_Lugares_seq"'::regclass),
    CONSTRAINT "Lugares_pkey" PRIMARY KEY ("Cod_Lugares")
);

CREATE TABLE IF NOT EXISTS public."Rutas"
(
    "Cod_Conductor" integer NOT NULL,
    "Cod_Bus" integer NOT NULL,
    "Cod_Lugar" integer NOT NULL,
    "Fecha" date NOT NULL,
    "Cod_Ruta" integer NOT NULL DEFAULT nextval('"Rutas_Cod_Ruta_seq"'::regclass),
    CONSTRAINT "Rutas_pkey" PRIMARY KEY ("Cod_Ruta")
);

ALTER TABLE IF EXISTS public."Rutas"
    ADD CONSTRAINT "FK_rutas_autobuses" FOREIGN KEY ("Cod_Bus")
    REFERENCES public."Autobuses" ("Cod_Bus") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rutas"
    ADD CONSTRAINT "Fk_rutas_conductores" FOREIGN KEY ("Cod_Conductor")
    REFERENCES public."Conductor" ("Cod_Conductor") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;